### ISSUE TITLE
老板要内定 怎么办 急 在线等

### ISSUE THREAD

**Issue by sky-gg** [onthedesk/3DLottery#1]
现场有一百个人 结果从特定的十个人里抽两个

**Comment by onthedesk** [comment]
> 现场有一百个人 结果从特定的十个人里抽两个

用两个数组存一下，展示的时候全部展示，抽奖的时候在内定的人里抽

**Comment by sky-gg** [comment]
> > 现场有一百个人结果从特定的十个人里抽两个
> 
> 用两个数组存一下，展示的时候全部展示，抽奖的时候在内定的人里抽

滚动的时候屏幕上不是也要实时显示嘛，万一显示暂停的和实际抽到的不一致呢？

**Comment by onthedesk** [comment]
> > > 现场有一百个人结果从特定的十个人里抽两个
> > 
> > 
> > 用两个数组存一下，展示的时候全部展示，抽奖的时候在内定的人里抽
> 
> 滚动的时候屏幕上不是也要实时显示嘛，万一显示暂停的和实际抽到的不一致呢？

暂停显示的图片也是用内定的人啊

**Comment by sky-gg** [comment]
> > > > 现场有一百个人结果从特定的十个人里抽两个
> > > 
> > > 
> > > 用两个数组存一下，展示的时候全部展示，抽奖的时候在内定的人里抽
> > 
> > 
> > 滚动的时候屏幕上不是也要实时显示嘛，万一显示暂停的和实际抽到的不一致呢？
> 
> 暂停显示的图片也是用内定的人啊

切换名字是有点明显哇
